name: 'vue-plu-cheatsheet'

services:
  backend:
    build: ./services/backend
    volumes:
      - ./services/backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - 5052:5052
    restart: always

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - 8082:8082
    restart: always

volumes:
  backend_node_modules:
  frontend_node_modules: