name: 'vue-plu-cheatsheet'

services:
  backend:
    build: ./services/backend
    volumes:
      - ./services/backend:/app
      - '/app/node_modules'
    ports:
      - 5052:5052

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8082:8082