version: '3.8'

services:
  backend:
    build: ./services/backend
    volumes:
      - ./services/backend:/app
    ports:
      - 5050:5050

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080